spring: 
  datasource: 
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: po
    password: po1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true
server:
  port: 9093